name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

env:
    GAR_LOCATION: europe-west4

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Go
        uses: actions/setup-go@v4
        with:
            go-version-file: 'go.mod'

      - name: Run Tests
        run: go test ./...

  build-and-push-docker:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Google Artefact Registry
        uses: docker/login-action@v2
        with:
            registry: ${{env.GAR_LOCATION}}-docker.pkg.dev
            username: _json_key
            password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/my-project/my-image:$GITHUB_SHA .
          docker push gcr.io/my-project/my-image:$GITHUB_SHA
